steps:
  # Create docker image
  - name: gcr.io/cloud-builders/docker
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build --build-arg="COMMUNITY_NAME=$_COMMUNITY_NAME" \
        --build-arg="SLACK_URL=$_SLACK_URL" \
        --build-arg="SLACK_TOKEN=$$SLACK_TOKEN" \
        -t 'gcr.io/$PROJECT_ID/slack-inviter' .
    secretEnv: ['SLACK_TOKEN']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/slack-inviter']

  # Start up a cloud instance
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'slack-inviter',
        '--image', 'gcr.io/$PROJECT_ID/slack-inviter',
        '--allow-unauthenticated',
        '--platform=managed',
        '--region=europe-west1'
      ]

# Image name
images: ['gcr.io/$PROJECT_ID/slack-inviter']
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/SLACK_TOKEN/versions/latest
      env: 'SLACK_TOKEN'
