FROM node:19-alpine
ARG COMMUNITY_NAME
ARG SLACK_URL
ARG SLACK_TOKEN
ENV COMMUNITY_NAME=${COMMUNITY_NAME}
ENV SLACK_URL=${SLACK_URL}
ENV SLACK_TOKEN=${SLACK_TOKEN}

EXPOSE 3000

COPY . /slack-invite-automation
WORKDIR /slack-invite-automation

RUN npm install

CMD node ./bin/www
