FROM node:19-alpine
ARG _COMMUNITY_NAME
ARG _SLACK_URL
ARG SLACK_TOKEN
ENV COMMUNITY_NAME=${_COMMUNITY_NAME}
ENV SLACK_URL=${_SLACK_URL}
ENV SLACK_TOKEN=${SLACK_TOKEN}

EXPOSE 3000

COPY . /slack-invite-automation
WORKDIR /slack-invite-automation

RUN npm install

CMD node ./bin/www